//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/_Project/Input/GameInput.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

namespace InputSystem
{
    public partial class @GameInput: IInputActionCollection2, IDisposable
    {
        public InputActionAsset asset { get; }
        public @GameInput()
        {
            asset = InputActionAsset.FromJson(@"{
    ""name"": ""GameInput"",
    ""maps"": [
        {
            ""name"": ""Player"",
            ""id"": ""a1b2c3d4-e5f6-7890-abcd-ef1234567890"",
            ""actions"": [
                {
                    ""name"": ""Move"",
                    ""type"": ""Value"",
                    ""id"": ""b2c3d4e5-f6a7-8901-bcde-f12345678901"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Pause"",
                    ""type"": ""Button"",
                    ""id"": ""c3d4e5f6-a7b8-9012-cdef-123456789012"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""PortFire1"",
                    ""type"": ""Button"",
                    ""id"": ""d4e5f6a7-b8c9-0123-defa-234567890123"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""PortFire2"",
                    ""type"": ""Button"",
                    ""id"": ""e5f6a7b8-c9d0-1234-efab-345678901234"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""PortFire3"",
                    ""type"": ""Button"",
                    ""id"": ""f6a7b8c9-d0e1-2345-fabc-456789012345"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""PortFire4"",
                    ""type"": ""Button"",
                    ""id"": ""a7b8c9d0-e1f2-3456-abcd-567890123456"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""PortFire5"",
                    ""type"": ""Button"",
                    ""id"": ""b8c9d0e1-f2a3-4567-bcde-678901234567"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""PortFire6"",
                    ""type"": ""Button"",
                    ""id"": ""c9d0e1f2-a3b4-5678-cdef-789012345678"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""PortFire7"",
                    ""type"": ""Button"",
                    ""id"": ""d0e1f2a3-b4c5-6789-defa-890123456789"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""PortFire8"",
                    ""type"": ""Button"",
                    ""id"": ""e1f2a3b4-c5d6-7890-efab-901234567890"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""f2a3b4c5-d6e7-8901-fabc-012345678901"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""a3b4c5d6-e7f8-9012-abcd-123456789012"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""up"",
                    ""id"": ""b4c5d6e7-f8a9-0123-bcde-234567890123"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""c5d6e7f8-a9b0-1234-cdef-345678901234"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""d6e7f8a9-b0c1-2345-defa-456789012345"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""e7f8a9b0-c1d2-3456-efab-567890123456"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""f8a9b0c1-d2e3-4567-fabc-678901234567"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""a9b0c1d2-e3f4-5678-abcd-789012345678"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""b0c1d2e3-f4a5-6789-bcde-890123456789"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""c1d2e3f4-a5b6-7890-cdef-901234567890"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Pause"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d2e3f4a5-b6c7-8901-defa-012345678901"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PortFire1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e3f4a5b6-c7d8-9012-efab-123456789012"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PortFire2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f4a5b6c7-d8e9-0123-fabc-234567890123"",
                    ""path"": ""<Keyboard>/3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PortFire3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a5b6c7d8-e9f0-1234-abcd-345678901234"",
                    ""path"": ""<Keyboard>/4"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PortFire4"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b6c7d8e9-f0a1-2345-bcde-456789012345"",
                    ""path"": ""<Keyboard>/5"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PortFire5"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c7d8e9f0-a1b2-3456-cdef-567890123456"",
                    ""path"": ""<Keyboard>/6"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PortFire6"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d8e9f0a1-b2c3-4567-defa-678901234567"",
                    ""path"": ""<Keyboard>/7"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PortFire7"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e9f0a1b2-c3d4-5678-efab-789012345678"",
                    ""path"": ""<Keyboard>/8"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PortFire8"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
            // Player
            m_Player = asset.FindActionMap("Player", throwIfNotFound: true);
            m_Player_Move = m_Player.FindAction("Move", throwIfNotFound: true);
            m_Player_Pause = m_Player.FindAction("Pause", throwIfNotFound: true);
            m_Player_PortFire1 = m_Player.FindAction("PortFire1", throwIfNotFound: true);
            m_Player_PortFire2 = m_Player.FindAction("PortFire2", throwIfNotFound: true);
            m_Player_PortFire3 = m_Player.FindAction("PortFire3", throwIfNotFound: true);
            m_Player_PortFire4 = m_Player.FindAction("PortFire4", throwIfNotFound: true);
            m_Player_PortFire5 = m_Player.FindAction("PortFire5", throwIfNotFound: true);
            m_Player_PortFire6 = m_Player.FindAction("PortFire6", throwIfNotFound: true);
            m_Player_PortFire7 = m_Player.FindAction("PortFire7", throwIfNotFound: true);
            m_Player_PortFire8 = m_Player.FindAction("PortFire8", throwIfNotFound: true);
        }

        public void Dispose()
        {
            UnityEngine.Object.Destroy(asset);
        }

        public InputBinding? bindingMask
        {
            get => asset.bindingMask;
            set => asset.bindingMask = value;
        }

        public ReadOnlyArray<InputDevice>? devices
        {
            get => asset.devices;
            set => asset.devices = value;
        }

        public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

        public bool Contains(InputAction action)
        {
            return asset.Contains(action);
        }

        public IEnumerator<InputAction> GetEnumerator()
        {
            return asset.GetEnumerator();
        }

        IEnumerator IEnumerable.GetEnumerator()
        {
            return GetEnumerator();
        }

        public void Enable()
        {
            asset.Enable();
        }

        public void Disable()
        {
            asset.Disable();
        }

        public IEnumerable<InputBinding> bindings => asset.bindings;

        public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
        {
            return asset.FindAction(actionNameOrId, throwIfNotFound);
        }

        public int FindBinding(InputBinding bindingMask, out InputAction action)
        {
            return asset.FindBinding(bindingMask, out action);
        }

        // Player
        private readonly InputActionMap m_Player;
        private List<IPlayerActions> m_PlayerActionsCallbackInterfaces = new List<IPlayerActions>();
        private readonly InputAction m_Player_Move;
        private readonly InputAction m_Player_Pause;
        private readonly InputAction m_Player_PortFire1;
        private readonly InputAction m_Player_PortFire2;
        private readonly InputAction m_Player_PortFire3;
        private readonly InputAction m_Player_PortFire4;
        private readonly InputAction m_Player_PortFire5;
        private readonly InputAction m_Player_PortFire6;
        private readonly InputAction m_Player_PortFire7;
        private readonly InputAction m_Player_PortFire8;
        public struct PlayerActions
        {
            private @GameInput m_Wrapper;
            public PlayerActions(@GameInput wrapper) { m_Wrapper = wrapper; }
            public InputAction @Move => m_Wrapper.m_Player_Move;
            public InputAction @Pause => m_Wrapper.m_Player_Pause;
            public InputAction @PortFire1 => m_Wrapper.m_Player_PortFire1;
            public InputAction @PortFire2 => m_Wrapper.m_Player_PortFire2;
            public InputAction @PortFire3 => m_Wrapper.m_Player_PortFire3;
            public InputAction @PortFire4 => m_Wrapper.m_Player_PortFire4;
            public InputAction @PortFire5 => m_Wrapper.m_Player_PortFire5;
            public InputAction @PortFire6 => m_Wrapper.m_Player_PortFire6;
            public InputAction @PortFire7 => m_Wrapper.m_Player_PortFire7;
            public InputAction @PortFire8 => m_Wrapper.m_Player_PortFire8;
            public InputActionMap Get() { return m_Wrapper.m_Player; }
            public void Enable() { Get().Enable(); }
            public void Disable() { Get().Disable(); }
            public bool enabled => Get().enabled;
            public static implicit operator InputActionMap(PlayerActions set) { return set.Get(); }
            public void AddCallbacks(IPlayerActions instance)
            {
                if (instance == null || m_Wrapper.m_PlayerActionsCallbackInterfaces.Contains(instance)) return;
                m_Wrapper.m_PlayerActionsCallbackInterfaces.Add(instance);
                @Move.started += instance.OnMove;
                @Move.performed += instance.OnMove;
                @Move.canceled += instance.OnMove;
                @Pause.started += instance.OnPause;
                @Pause.performed += instance.OnPause;
                @Pause.canceled += instance.OnPause;
                @PortFire1.started += instance.OnPortFire1;
                @PortFire1.performed += instance.OnPortFire1;
                @PortFire1.canceled += instance.OnPortFire1;
                @PortFire2.started += instance.OnPortFire2;
                @PortFire2.performed += instance.OnPortFire2;
                @PortFire2.canceled += instance.OnPortFire2;
                @PortFire3.started += instance.OnPortFire3;
                @PortFire3.performed += instance.OnPortFire3;
                @PortFire3.canceled += instance.OnPortFire3;
                @PortFire4.started += instance.OnPortFire4;
                @PortFire4.performed += instance.OnPortFire4;
                @PortFire4.canceled += instance.OnPortFire4;
                @PortFire5.started += instance.OnPortFire5;
                @PortFire5.performed += instance.OnPortFire5;
                @PortFire5.canceled += instance.OnPortFire5;
                @PortFire6.started += instance.OnPortFire6;
                @PortFire6.performed += instance.OnPortFire6;
                @PortFire6.canceled += instance.OnPortFire6;
                @PortFire7.started += instance.OnPortFire7;
                @PortFire7.performed += instance.OnPortFire7;
                @PortFire7.canceled += instance.OnPortFire7;
                @PortFire8.started += instance.OnPortFire8;
                @PortFire8.performed += instance.OnPortFire8;
                @PortFire8.canceled += instance.OnPortFire8;
            }

            private void UnregisterCallbacks(IPlayerActions instance)
            {
                @Move.started -= instance.OnMove;
                @Move.performed -= instance.OnMove;
                @Move.canceled -= instance.OnMove;
                @Pause.started -= instance.OnPause;
                @Pause.performed -= instance.OnPause;
                @Pause.canceled -= instance.OnPause;
                @PortFire1.started -= instance.OnPortFire1;
                @PortFire1.performed -= instance.OnPortFire1;
                @PortFire1.canceled -= instance.OnPortFire1;
                @PortFire2.started -= instance.OnPortFire2;
                @PortFire2.performed -= instance.OnPortFire2;
                @PortFire2.canceled -= instance.OnPortFire2;
                @PortFire3.started -= instance.OnPortFire3;
                @PortFire3.performed -= instance.OnPortFire3;
                @PortFire3.canceled -= instance.OnPortFire3;
                @PortFire4.started -= instance.OnPortFire4;
                @PortFire4.performed -= instance.OnPortFire4;
                @PortFire4.canceled -= instance.OnPortFire4;
                @PortFire5.started -= instance.OnPortFire5;
                @PortFire5.performed -= instance.OnPortFire5;
                @PortFire5.canceled -= instance.OnPortFire5;
                @PortFire6.started -= instance.OnPortFire6;
                @PortFire6.performed -= instance.OnPortFire6;
                @PortFire6.canceled -= instance.OnPortFire6;
                @PortFire7.started -= instance.OnPortFire7;
                @PortFire7.performed -= instance.OnPortFire7;
                @PortFire7.canceled -= instance.OnPortFire7;
                @PortFire8.started -= instance.OnPortFire8;
                @PortFire8.performed -= instance.OnPortFire8;
                @PortFire8.canceled -= instance.OnPortFire8;
            }

            public void RemoveCallbacks(IPlayerActions instance)
            {
                if (m_Wrapper.m_PlayerActionsCallbackInterfaces.Remove(instance))
                    UnregisterCallbacks(instance);
            }

            public void SetCallbacks(IPlayerActions instance)
            {
                foreach (var item in m_Wrapper.m_PlayerActionsCallbackInterfaces)
                    UnregisterCallbacks(item);
                m_Wrapper.m_PlayerActionsCallbackInterfaces.Clear();
                AddCallbacks(instance);
            }
        }
        public PlayerActions @Player => new PlayerActions(this);
        public interface IPlayerActions
        {
            void OnMove(InputAction.CallbackContext context);
            void OnPause(InputAction.CallbackContext context);
            void OnPortFire1(InputAction.CallbackContext context);
            void OnPortFire2(InputAction.CallbackContext context);
            void OnPortFire3(InputAction.CallbackContext context);
            void OnPortFire4(InputAction.CallbackContext context);
            void OnPortFire5(InputAction.CallbackContext context);
            void OnPortFire6(InputAction.CallbackContext context);
            void OnPortFire7(InputAction.CallbackContext context);
            void OnPortFire8(InputAction.CallbackContext context);
        }
    }
}
